package frc.robot;

import static edu.wpi.first.units.Units.*;

import com.ctre.phoenix6.configs.Slot0Configs;
import edu.wpi.first.math.system.plant.DCMotor;
import edu.wpi.first.units.measure.Angle;
import edu.wpi.first.units.measure.Distance;
import edu.wpi.first.units.measure.LinearVelocity;
import edu.wpi.first.units.measure.Mass;
import edu.wpi.first.units.measure.MomentOfInertia;
import edu.wpi.first.units.measure.Time;
import edu.wpi.first.units.measure.Voltage;
import edu.wpi.first.wpilibj.RobotBase;
import frc.robot.generated.TunerConstants;

public final class Constants {
  public static final Mode MODE = RobotBase.isReal() ? Mode.REAL : Mode.SIM;

  public static enum Mode {
    REAL,
    SIM,
    REPLAY
  }

  // WPILib 20ms default update period
  public static final Time UPDATE_PERIOD = Milliseconds.of(20);

  public static final class Motors {
    // https://docs.wcproducts.com/kraken-x44/kraken-x44-motor/overview-and-features/motor-performance
    public static final DCMotor KRAKEN_X44 =
        new DCMotor(
            12.0, // Nominal voltage (V)
            4.05, // Stall torque (Nm)
            275.0, // Stall current (A)
            1.4, // Free current (A)
            7530.0 * 2 * Math.PI / 60, // Free speed (rad/s)
            1 // Number of motors
            );
  }

  public static final class SimSwerveConstants {
    // TODO: update constants to what's physically on the robot
    public static final Mass ROBOT_MASS = Kilograms.of(64.0);
    public static final Distance BUMPER_LENGTH_X = Meters.of(0.792);
    public static final Distance BUMPER_LENGTH_Y = Meters.of(0.919);
    public static final double WHEEL_COF = 1.2;
    public static final DCMotor DRIVE_MOTOR_WHEEL = DCMotor.getKrakenX60(1);
    public static final DCMotor STEER_MOTOR_WHEEL = DCMotor.getKrakenX60(1);

    // Use values from generated TunerConstants where available to avoid duplicate
    // definitions. TunerConstants is generated by the Tuner tool and must not be
    // edited; prefer those values for module/drivetrain tuning parameters.
    public static final Slot0Configs STEER_MOTOR_GAINS = TunerConstants.FrontLeft.SteerMotorGains;
    public static final double STEER_MOTOR_GEAR_RATIO =
        TunerConstants.FrontLeft.SteerMotorGearRatio;
    public static final Voltage DRIVE_FRICTION_VOLTAGE =
        Volts.of(TunerConstants.FrontLeft.DriveFrictionVoltage);
    public static final Voltage STEER_FRICTION_VOLTAGE =
        Volts.of(TunerConstants.FrontLeft.SteerFrictionVoltage);
    public static final MomentOfInertia STEER_INERTIA =
        KilogramSquareMeters.of(TunerConstants.FrontLeft.SteerInertia);
  }

  public static final class AutoAlignConstants {
    // Constants for PID control
    public static final double DISTANCE_KP = 5.0;
    public static final double DISTANCE_KI = 0.0;
    public static final double DISTANCE_KD = 0.2;

    public static final double DISTANCE_FF = 0.0;
    public static final Distance DISTANCE_PID_TOLERANCE = Meters.of(0.02);

    public static final double ROTATION_KP = 3.5;
    public static final double ROTATION_KI = 0.0;
    public static final double ROTATION_KD = 0.0;

    // Max velocity used to clamp output
    public static final LinearVelocity MAX_TRANSLATION_VELOCITY = MetersPerSecond.of(4.5);

    // Tolerable error before stopping auto align
    public static final Distance NORMAL_TOLERANCE = Meters.of(0.1);
    public static final Distance TANGENT_TOLERANCE = Meters.of(0.1);
    public static final Angle ROTATION_TOLERANCE = Degrees.of(3);
  }
}
